"""Backend-agnostic helpers for building the Triton model repository.

Used by every `backends/<family>/export.py` and `triton_repo.py`. Keeps torch
out of the picture: `build_config_pbtxt` / `inspect_onnx` only need `onnx`.

The metadata dict written into `config.pbtxt` is the contract between a
backend's exporter and the same backend's Rust crate. Fields every backend
writes (parsed by `backend-api` `CommonMeta`):

family      : str, selects the gateway backend (e.g. "yolo", "rfdetr")
task        : "detect"
names       : list[str], indexed by class id
imgsz       : int, native square input resolution served by Triton
input       : str, ONNX input tensor name
outputs     : list[str], ONNX output tensor names (in request order)

Backends add their own fields (see backends/<family>/README.md).
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

_ONNX_DTYPE_TO_TRITON = {
    1: ("FP32", "TYPE_FP32"),   # float
    10: ("FP16", "TYPE_FP16"),  # float16
    11: ("FP64", "TYPE_FP64"),
}


def _escape_proto_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_config_pbtxt(
    *,
    model_name: str,
    metadata: dict[str, Any],
    input_spec: dict[str, Any],
    output_specs: list[dict[str, Any]],
    max_batch_size: int = 8,
    queue_delay_us: int = 4000,
    preferred_batch_sizes: tuple[int, ...] = (4, 8),
    instance_group_count: int | None = None,
) -> str:
    """Render a Triton `config.pbtxt` for an onnxruntime detection model.

    With `max_batch_size=0` the io specs carry full graph dims (batch
    included) and concurrency comes from `instance_group_count` instead of
    dynamic batching.
    """
    meta_json = json.dumps(metadata, separators=(",", ":"), ensure_ascii=True)

    lines = [
        f"# Auto-generated by backends/<family> tooling for '{model_name}'. Do not edit by hand.",
        'backend: "onnxruntime"',
        f"name: {_escape_proto_string(model_name)}",
        f"max_batch_size: {max_batch_size}",
    ]
    if max_batch_size >= 2:
        preferred = ", ".join(str(b) for b in preferred_batch_sizes if b <= max_batch_size)
        lines += [
            "dynamic_batching {",
            f"  preferred_batch_size: [{preferred}]",
            f"  max_queue_delay_microseconds: {queue_delay_us}",
            "}",
        ]
    elif instance_group_count:
        lines += ["instance_group [", f"  {{ count: {instance_group_count} }}", "]"]
    head = "\n".join(lines + ["input ["])
    body = _render_entries([input_spec]) + "]\noutput [\n" + _render_entries(output_specs) + "]"
    tail = (
        "\nparameters {\n"
        '  key: "metadata"\n'
        f"  value {{ string_value: {_escape_proto_string(meta_json)} }}\n"
        "}\n"
    )
    return head + "\n" + body + tail


def _render_entries(specs: list[dict[str, Any]]) -> str:
    out = []
    for s in specs:
        dims = ", ".join(str(d) for d in s["dims"])
        out.append(
            "  {\n"
            f"    name: {_escape_proto_string(s['name'])}\n"
            f"    data_type: {s['data_type']}\n"
            f"    dims: [ {dims} ]\n"
            "  }"
        )
    return ",\n".join(out) + "\n"


def inspect_onnx(path: Path) -> dict[str, Any]:
    """Return input/output tensor names, element types and (symbolic) dims."""
    import onnx

    model = onnx.load(str(path))
    graph = model.graph
    init_names = {i.name for i in graph.initializer}

    def elem_type(value_info):
        return value_info.type.tensor_type.elem_type

    def dims(value_info):
        tt = value_info.type.tensor_type
        res = []
        for d in tt.shape.dim:
            if d.HasField("dim_value"):
                res.append(int(d.dim_value))
            else:
                res.append(d.dim_param or "?")
        return res

    inputs = [
        {"name": i.name, "elem": elem_type(i), "dims": dims(i)}
        for i in graph.input
        if i.name not in init_names
    ]
    outputs = [
        {"name": o.name, "elem": elem_type(o), "dims": dims(o)} for o in graph.output
    ]
    if len(inputs) != 1:
        raise ValueError(f"expected exactly 1 ONNX input, got {[i['name'] for i in inputs]}")
    return {"input": inputs[0], "outputs": outputs}


def dense_names(names: dict[int, str] | list[str], n: int, prefix: str = "class_") -> list[str]:
    """Normalize ultralytics/rfdetr name mappings to a list indexed by id."""
    if isinstance(names, dict):
        return [names.get(i, f"{prefix}{i}") for i in range(n)]
    out = list(names[:n])
    while len(out) < n:
        out.append(f"{prefix}{len(out)}")
    return out


def triton_dtype(onnx_elem: int) -> str:
    """Map an ONNX element type id to Triton's TYPE_* enum name."""
    return _ONNX_DTYPE_TO_TRITON.get(onnx_elem, ("FP32", "TYPE_FP32"))[1]


def write_repo(
    repo_dir: Path,
    model_name: str,
    onnx_path: Path,
    config_text: str,
) -> Path:
    model_dir = repo_dir / model_name
    version_dir = model_dir / "1"
    version_dir.mkdir(parents=True, exist_ok=True)
    dest = version_dir / "model.onnx"
    if onnx_path.resolve() != dest.resolve():
        shutil.copy2(onnx_path, dest)
    (model_dir / "config.pbtxt").write_text(config_text)
    return model_dir


ROOT = Path(__file__).resolve().parents[1]
BACKENDS_DIR = ROOT / "backends"


def load_backend_modules(module: str = "triton_repo") -> dict[str, Any]:
    """Import `backends/<family>/<module>.py` for every backend folder.

    Returns {family: module}. Each module must define `FAMILY`.
    """
    import importlib.util

    found: dict[str, Any] = {}
    for path in sorted(BACKENDS_DIR.glob(f"*/{module}.py")):
        spec = importlib.util.spec_from_file_location(f"backend_{path.parent.name}_{module}", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        found[mod.FAMILY] = mod
    return found


def has_dynamic_batch(dims: list) -> bool:
    """True if an ONNX tensor's first dim is symbolic (required by Triton
    whenever `max_batch_size > 0`)."""
    return bool(dims) and not isinstance(dims[0], int)


def check_onnx_matches_batching(onnx_path: Path, max_batch_size: int) -> None:
    """Enforce Triton's rule: a batching model (max_batch_size > 0) must have a
    dynamic first dim on every input; a non-batching one may be static."""
    if max_batch_size <= 0:
        return
    info = inspect_onnx(onnx_path)
    dims = info["input"]["dims"]
    if not has_dynamic_batch(dims):
        raise AssertionError(
            f"max_batch_size={max_batch_size} but ONNX input '{info['input']['name']}' has a "
            f"static batch dim {dims}; Triton will refuse to load it. Re-export with a dynamic "
            "batch or set max_batch_size: 0 with explicit full dims."
        )


def batched_constant_onnx(path: Path, input_name: str, imgsz: int,
                          outputs: dict[str, Any]) -> None:
    """Write a fixture ONNX with a DYNAMIC batch input `[batch, 3, imgsz, imgsz]`
    whose outputs are the given constant arrays (each shaped `[1, ...]`)
    broadcast to `[batch, ...]`. Loadable by real Triton with max_batch_size > 0.
    """
    import numpy as np
    import onnx
    from onnx import TensorProto, helper, numpy_helper

    nodes = [
        # zeros of shape [batch, 1, 1]: ReduceMean(input) * 0, reshaped
        helper.make_node("ReduceMean", [input_name], ["_mean"], axes=[1, 2, 3], keepdims=1),
        helper.make_node("Mul", ["_mean", "_zero"], ["_zeros4"]),
        helper.make_node("Reshape", ["_zeros4", "_shape3"], ["_zeros"]),
    ]
    inits = [
        numpy_helper.from_array(np.zeros((1,), dtype=np.float32), "_zero"),
        numpy_helper.from_array(np.array([-1, 1, 1], dtype=np.int64), "_shape3"),
    ]
    outs = []
    for name, arr in outputs.items():
        arr = np.asarray(arr, dtype=np.float32)
        assert arr.ndim == 3 and arr.shape[0] == 1, f"{name}: expected [1, a, b], got {arr.shape}"
        inits.append(numpy_helper.from_array(arr, f"{name}_const"))
        nodes.append(helper.make_node("Add", ["_zeros", f"{name}_const"], [name]))
        outs.append(helper.make_tensor_value_info(name, TensorProto.FLOAT, ["batch", *arr.shape[1:]]))
    graph = helper.make_graph(
        nodes, "fixture",
        [helper.make_tensor_value_info(input_name, TensorProto.FLOAT, ["batch", 3, imgsz, imgsz])],
        outs, inits,
    )
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 17)])
    model.ir_version = 9
    onnx.checker.check_model(model)
    onnx.save(model, str(path))
